from __future__ import annotations

import sys
from pathlib import Path


API_ROOT = Path(__file__).resolve().parents[1]
if str(API_ROOT) not in sys.path:
    sys.path.insert(0, str(API_ROOT))

from app.convert import mineru_adapter


def test_recover_missing_notebooklm_footer_elements_applies_page_index_shift() -> None:
    ir = {
        "pages": [
            {
                "page_index": 0,
                "page_width_pt": 1000.0,
                "page_height_pt": 1000.0,
                "has_text_layer": True,
                "elements": [
                    {
                        "type": "text",
                        "bbox_pt": [120.0, 120.0, 520.0, 180.0],
                        "text": "Page 1 title",
                        "source": "mineru",
                    }
                ],
            },
            {
                "page_index": 1,
                "page_width_pt": 1000.0,
                "page_height_pt": 1000.0,
                "has_text_layer": True,
                "elements": [
                    {
                        "type": "text",
                        "bbox_pt": [120.0, 120.0, 520.0, 180.0],
                        "text": "Page 2 title",
                        "source": "mineru",
                    }
                ],
            },
        ]
    }

    recovered = mineru_adapter._recover_missing_notebooklm_footer_elements(
        ir=ir,
        content_items=[
            {
                "page_idx": 1,
                "type": "footer",
                "bbox": [872.0, 944.0, 972.0, 968.0],
                "text": "NotebookLM",
            },
            {
                "page_idx": 2,
                "type": "footer",
                "bbox": [874.0, 946.0, 974.0, 970.0],
                "text": "AI generated by NotebookLM",
            },
        ],
        source_pdf=Path("/tmp/nonexistent.pdf"),
        page_sizes={0: (1000.0, 1000.0), 1: (1000.0, 1000.0)},
    )

    assert recovered == 2
    assert [
        el["text"]
        for el in ir["pages"][0]["elements"]
        if "notebooklm" in str(el.get("text") or "").lower()
    ] == ["NotebookLM"]
    assert [
        el["text"]
        for el in ir["pages"][1]["elements"]
        if "notebooklm" in str(el.get("text") or "").lower()
    ] == ["AI generated by NotebookLM"]


def test_recover_missing_notebooklm_footer_elements_skips_non_footer_mentions() -> None:
    ir = {
        "pages": [
            {
                "page_index": 0,
                "page_width_pt": 1000.0,
                "page_height_pt": 1000.0,
                "has_text_layer": True,
                "elements": [],
            }
        ]
    }

    recovered = mineru_adapter._recover_missing_notebooklm_footer_elements(
        ir=ir,
        content_items=[
            {
                "page_idx": 0,
                "type": "text",
                "bbox": [180.0, 180.0, 360.0, 220.0],
                "text": "NotebookLM",
            },
            {
                "page_idx": 0,
                "type": "footer",
                "bbox": [880.0, 948.0, 980.0, 972.0],
                "text": "NotebookLM",
            },
        ],
        source_pdf=Path("/tmp/nonexistent.pdf"),
        page_sizes={0: (1000.0, 1000.0)},
    )

    assert recovered == 1
    assert [
        el["bbox_pt"]
        for el in ir["pages"][0]["elements"]
        if "notebooklm" in str(el.get("text") or "").lower()
    ] == [[880.0, 948.0, 980.0, 972.0]]


def test_recover_missing_notebooklm_footer_elements_deduplicates_existing_footer() -> None:
    ir = {
        "pages": [
            {
                "page_index": 0,
                "page_width_pt": 1000.0,
                "page_height_pt": 1000.0,
                "has_text_layer": True,
                "elements": [
                    {
                        "type": "text",
                        "bbox_pt": [880.0, 948.0, 980.0, 972.0],
                        "text": "NotebookLM",
                        "source": "mineru",
                        "mineru_block_type": "footer",
                    }
                ],
            }
        ]
    }

    recovered = mineru_adapter._recover_missing_notebooklm_footer_elements(
        ir=ir,
        content_items=[
            {
                "page_idx": 0,
                "type": "footer",
                "bbox": [881.0, 949.0, 981.0, 973.0],
                "text": "AI generated by NotebookLM",
            }
        ],
        source_pdf=Path("/tmp/nonexistent.pdf"),
        page_sizes={0: (1000.0, 1000.0)},
    )

    assert recovered == 0
    assert len(ir["pages"][0]["elements"]) == 1
