"""OCR package facade preserving previous public imports."""

from .ai_client import (
    AiOcrClient,
    AiOcrTextRefiner,
    _is_multiline_candidate_for_linebreak_assist,
)
from .base import OcrProvider
from .deepseek_parser import _extract_deepseek_tagged_items
from .local_providers import (
    BaiduOcrClient,
    OcrManager,
    PaddleOcrClient,
    TesseractOcrClient,
    _dedupe_overlapping_ocr_items,
    create_remote_ocr_client,
    create_ocr_manager,
    ocr_image_to_elements,
    probe_local_paddle_models,
    probe_local_paddleocr,
    probe_local_tesseract_models,
    probe_local_tesseract,
    resolve_remote_ocr_client_spec,
)
from .routing import (
    OcrRoutePlan,
    ROUTE_KIND_HYBRID_AUTO,
    ROUTE_KIND_LOCAL_LAYOUT_BLOCK_OCR,
    ROUTE_KIND_MACHINE_OCR,
    ROUTE_KIND_REMOTE_DOC_PARSER,
    ROUTE_KIND_REMOTE_PROMPT_OCR,
    ROUTE_KIND_UNKNOWN,
    build_ocr_route_plan,
    normalize_ocr_route_kind,
    should_allow_main_ai_reuse,
)
from .utils import _coerce_bbox_xyxy
from .vendors import (
    AiOcrVendorAdapter,
    AiOcrVendorProfile,
    DeepSeekAiOcrAdapter,
    NovitaAiOcrAdapter,
    OpenAiAiOcrAdapter,
    PpioAiOcrAdapter,
    SiliconFlowAiOcrAdapter,
)

__all__ = [
    "AiOcrClient",
    "AiOcrTextRefiner",
    "AiOcrVendorAdapter",
    "AiOcrVendorProfile",
    "BaiduOcrClient",
    "DeepSeekAiOcrAdapter",
    "NovitaAiOcrAdapter",
    "OcrManager",
    "OcrProvider",
    "OpenAiAiOcrAdapter",
    "OcrRoutePlan",
    "PaddleOcrClient",
    "PpioAiOcrAdapter",
    "ROUTE_KIND_HYBRID_AUTO",
    "ROUTE_KIND_LOCAL_LAYOUT_BLOCK_OCR",
    "ROUTE_KIND_MACHINE_OCR",
    "ROUTE_KIND_REMOTE_DOC_PARSER",
    "ROUTE_KIND_REMOTE_PROMPT_OCR",
    "ROUTE_KIND_UNKNOWN",
    "SiliconFlowAiOcrAdapter",
    "TesseractOcrClient",
    "_coerce_bbox_xyxy",
    "_dedupe_overlapping_ocr_items",
    "_extract_deepseek_tagged_items",
    "_is_multiline_candidate_for_linebreak_assist",
    "build_ocr_route_plan",
    "create_remote_ocr_client",
    "create_ocr_manager",
    "normalize_ocr_route_kind",
    "ocr_image_to_elements",
    "probe_local_paddle_models",
    "probe_local_paddleocr",
    "probe_local_tesseract_models",
    "probe_local_tesseract",
    "resolve_remote_ocr_client_spec",
    "should_allow_main_ai_reuse",
]
